import "dotenv/config";
import fs from "fs";
import path from "path";
import config, { DocNode } from "../docs.config";

const root = process.cwd();
const basePath = path.join(root, config.basePath || "app");



const DOCUMENTATION_INSTRUCTIONS = `
You are a technical documentation writer for a SaaS product.

Generate clear, user-facing documentation in clean Markdown suitable for MDX.

Use structured headings and step-by-step instructions with bulletpoints when helpful.
Focus on end users, not internal implementation.
Write in a way that is easy to understand for non-technical users.
Use proper Markdown formatting and fenced code blocks when needed.

Output only valid Markdown.
`;


async function callOpenAiApi(prompt: string): Promise<string> {
  const apiKey = process.env.OPENAI_API_KEY;

  if (!apiKey) {
    throw new Error("OPENAI_API_KEY is not defined");
  }

  const response = await fetch("https://api.openai.com/v1/responses", {
    method: "POST",
    headers: {
      Authorization: `Bearer ${apiKey}`,
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      model: "gpt-4.1-mini",
      instructions: DOCUMENTATION_INSTRUCTIONS,
      input: prompt,
      temperature: 0.3,
    }),
  });

  if (!response.ok) {
    const errText = await response.text();
    throw new Error(`API error ${response.status}: ${errText}`);
  }

  const data = await response.json();

  if (!data?.output?.length) {
    throw new Error("API returned no output.");
  }

  const text = data.output?.[0]?.content?.[0]?.text;

  if (!text) {
    throw new Error("Model returned no text output.");
  }

  return text.trim();
}

async function generateContent({
  title,
  description,
  prompt,
}: {
  title: string;
  description?: string;
  prompt: string;
}): Promise<string> {
  console.log("\nSending prompt to AI:");
  console.log("--------------------------------------------------");
  console.log(prompt.trim());
  console.log("--------------------------------------------------");

  const output = await callOpenAiApi(prompt);

  return `---
title: ${title}
description: ${description ?? ""}
---

# ${title}

**This content was generated by AI. Please verify correctness.**

---

${output}

---
`;
}

/**
 * Recursive page generator
 */

async function generatePages(
  nodes: Record<string, DocNode>,
  currentPath: string[] = [],
): Promise<void> {
  for (const [key, node] of Object.entries(nodes)) {
    const newPath = [...currentPath, key];
    const pageDir = path.join(basePath, ...newPath);
    const filePath = path.join(pageDir, "page.mdx");

    fs.mkdirSync(pageDir, { recursive: true });

    if (!fs.existsSync(filePath)) {
      const content = await generateContent({
        title: node.title,
        description: node.description,
        prompt: node.prompt,
      });

      fs.writeFileSync(filePath, content);
      console.log(`📄 Created: ${filePath}`);
    } else {
      console.log(`⚠️ Skipped (exists): ${filePath}`);
    }

    if (node.children) {
      await generatePages(node.children, newPath);
    }
  }
}

async function main() {
  console.log("Starting AI documentation generation...\n");
  await generatePages(config.pages);
  console.log("\nDocumentation generation complete.");
}

main().catch((err) => {
  console.error("Error during generation:");
  console.error(err);
  process.exit(1);
});
